app_names:
  - l2-indexer-micro-service
  - l2-indexer-worker-optimism-mainnet
  - l2-indexer-worker-optimism-sepolia
  - l2-indexer-worker-base-mainnet
  - l2-indexer-worker-base-sepolia
  - l2-indexer-worker-world-chain-sepolia
  - l2-indexer-worker-ape-chain-sepolia
  - l2-indexer-worker-ape-chain-mainnet
version_file: ./Cargo.toml
namespace: l2-indexer